### ISSUE TITLE
same

### ISSUE THREAD

**Issue by Zachberry777** [Montana-Media-Arts/441-WebTech-Spring2019#10]
Thank You Mark And Kaitlin, I tried both and looks like i got closer to what im looking for now i have this problem and could use help with that. 
![screenshot 38](https://user-images.githubusercontent.com/31712164/52982955-0ac85680-33a6-11e9-9953-936eeb7702b0.png)

**Comment by MarkLannen** [comment]
I think the reference in your script tag should look like this:

<script src="main.js"></script>

rather than href = ...

Let me know if that helps.

**Comment by Zachberry777** [comment]
Yes thank you mark that did help! It worked.

**Comment by MarkLannen** [comment]
Great!

**Comment by michaelcassens** [comment]
Hi Zach,

So, this just means that your method, printBlanks doesn't exist in your .js
file.

Hope this helps!

Michael

**Comment by Zachberry777** [comment]
So ive gotten far but now i can open my images past the first four open. how do i fix this 
![screenshot 39](https://user-images.githubusercontent.com/31712164/52985127-94c8ed00-33af-11e9-93c9-cb101491968f.png)
![screenshot 40](https://user-images.githubusercontent.com/31712164/52985129-98f50a80-33af-11e9-9a21-a79b63361a8f.png)
![screenshot 41](https://user-images.githubusercontent.com/31712164/52985131-9abece00-33af-11e9-99f7-7c3b40b9214f.png)

**Comment by MarkLannen** [comment]
In the while loop in your .js file, try increasing the number in the condition to 10. 

while(hiddenImages.length < 10)

And also make sure you increase the number of elements in the array to 5 0's.  

var count = [0, 0, 0, 0, 0];

Let me know if I'm on the right track!

**Comment by MarkLannen** [comment]
Also, in your html, make sure you update the id's of the images you've added. "image7", "image8", etc.

I got stuck on that one for a while...

**Comment by MarkLannen** [comment]
Sorry, didn't realize you had attached a screenshot of your html. It looks like you have that correct!

**Comment by Zachberry777** [comment]
![screenshot 42](https://user-images.githubusercontent.com/31712164/52986480-f93a7b00-33b4-11e9-8122-495bb5a71f5e.png)
![screenshot 43](https://user-images.githubusercontent.com/31712164/52986483-fa6ba800-33b4-11e9-877f-01b7e35a8e52.png)
Only lets me open 4 still but diffrent images of the four

**Comment by MarkLannen** [comment]
In the while loop, change the 4 to a 10, not in the if statement, which is where I think you made the change. I'm pretty sure that should go back to 2.

while(hiddenImages.length < 10)

Does that work?

**Comment by Zachberry777** [comment]
i did those just now and i still only get four when i click all of them, i dont get why it wont work, the while(hiddenImages.length <10) mine says while(actualImages.length <10)
![screenshot 44](https://user-images.githubusercontent.com/31712164/52987330-e8d7cf80-33b7-11e9-84dc-27719d3780b7.png)
![screenshot 45](https://user-images.githubusercontent.com/31712164/52987334-ea08fc80-33b7-11e9-86cd-34152dc1ccfb.png)

**Comment by MarkLannen** [comment]
Hmm... Can you post a screenshot of you html?

Thanks

**Comment by Zachberry777** [comment]
![screenshot 46](https://user-images.githubusercontent.com/31712164/52987814-f7bf8180-33b9-11e9-8d44-b72306d962d4.png)

**Comment by Zachberry777** [comment]
if not then i can ask Micheal, You really did help me alot, Thanks for that.

**Comment by MarkLannen** [comment]
I think I've got it. The parameters in your flipImage function need to ascend from 0 - 9. At the moment they go from 0-3 and then 2,3,2,3 etc.

Try that and let me know what happens.

**Comment by Zachberry777** [comment]
You are a genius, That was it thank you so much!

**Comment by MarkLannen** [comment]
I made the same error - took me ages to figure it out.  Glad it's working!
