### ISSUE TITLE
How to display the names and attempt

### ISSUE THREAD

**Issue by Dani-Briggs** [Montana-Media-Arts/441-WebTech-Spring2019#12]
Hi, I'm almost done with this assignment, the only problem being I can't figure out how to do the last half. I got the card flipping done, but I can't figure out for how to record the number of attempts or how to display everything else. I know it's probably very simple, but I'm not very good at coding and the examples aren't really helping me.

here's what I have so far
[https://github.com/Dani-Briggs/441/tree/master/Hw-6](url)

**Comment by michaelcassens** [comment]
Hi Dani,

First, you are doing a great job!  Don't sell yourself short.  You have all
done an amazing job so far.  As for completing this last part, you will
need a global variable.  Then, look inside your flip card function.  For
each attempt, increase your global variable by 1.

Then, when you are done, save your global variable value to your JSON
object and put it back into local storage.  Then, you can go the last page
and print everything out.

Hope this helps!

Michael

**Comment by ChristoffSomm** [comment]
Hey Dani, 

So what I did was I added a Score Variable and set it = 0. Then everytime the flipImage function is called I add one to the score Var. 

> 
var score = 0;


function flipImage(number) {
  if(firstNumber >= 0)
  {
    secNumber = number;
    document.getElementById(imageTags[number]).src = actualImages[secNumber];
  }
  else if (firstNumber < 0)
  {
    firstNumber = number;
    document.getElementById(imageTags[firstNumber]).src = actualImages[firstNumber];
  }
  if(actualImages[secNumber] != actualImages[firstNumber] && firstNumber >= 0 && secNumber >= 0)
  {
    setTimeout(imageDisappear, 900);
**// add to score
score++;
return score;**
  }
  else if(actualImages[secNumber] == actualImages[firstNumber] &&  firstNumber >= 0 && secNumber >= 0 )
  {
   firstNumber = -1;
   secNumber = -1;
**//Adds to Score
score++;
return score;**
  }
>






Don't forget to push the score Variable into JSON.  

Hope this helps
