### ISSUE TITLE
Images not flipping

### ISSUE THREAD

**Issue by ghost** [Montana-Media-Arts/441-WebTech-Spring2019#13]
Hi y'all!

Banging my head against this. By my understanding, the code should be working just fine but I think there must be something wrong with my flipImage function, as it just won't work for me.

If anyone could take a look and give me some insights that would be greatly appreciated.

Here's the Github directory: https://github.com/FinnVreugdenhil/441-work/tree/master/HW-6
and here's the Github page: https://finnvreugdenhil.github.io/441-work/HW-6/

**Comment by kaitlinclifford** [comment]
I had this problem too. It's really simple. In your script.js, your variable is imageTags, but you have things from his example code as imageNames... so you just have to change everything that has imageNames to imageTags... then your images should work again. Let me know if that works for you!

**Comment by ghost** [comment]
You're an angel, thank you for the help!
