### ISSUE TITLE
toString

### ISSUE THREAD

**Issue by rachel-holton-burnett** [Montana-Media-Arts/441-WebTech-Spring2019#14]
Hello! How do I add more returns to my toString? I can't add another return this.image; or another toString() 
{
return this.image;
}
I feel like I'm missing something really obvious and I can't put my finger on it. Here is the code I have so far (the alphabet letters are just junk data so I can see what's happening with it). Any tips on where to go from here would be appreciated! Thank you!

var myViewFinderArray = new Array();

class ViewFinder
{
    constructor(title,image,description,author,year)
    {
        this.title = title;
        this.image = image;
        this.description = description;
        this.author = author;
        this.year = year;
    }

    toString()
    {
      return "Title: " + this.title;

    }

    get theTitle()
    {
        return this.title;
    }
    get theImage()
    {
      return this.image;
    }
    get theDescription()
    {
      return this.description;
    }
    get theAuthor()
    {
      return this.author;
    }
    get theYear()
    {
      return this.year;
    }
  }

  function initializeArray()
  {
      var myViewFinder = new ViewFinder("abc", "def","ghi");
      var myViewFinder1 = new ViewFinder("jkl", "mno","pqr");
      myViewFinderArray.push(myViewFinder);
      myViewFinderArray.push(myViewFinder1);

  }

  function accessInformation()
  {
      /// random object from the array
      //console.log(myViewFinder.toString());
      //console.log(myViewFinder.theTitle);
      document.getElementById("title").innerHTML = myViewFinderArray[0].toString();
      document.getElementById("image").innerHTML = myViewFinderArray[0].toString();

  }

**Comment by michaelcassens** [comment]
Hi there,

You might try concatenate more items using the "+" symbol.

Hope this helps!

**Comment by rachel-holton-burnett** [comment]
Yes that did, thank you so much! Now I can't get the actual image to populate only the image tag. Can you steer me in the right direction? I've tried making a variable, document.Createlement, document.getElementById and obviously just putting the image tag in that field.

**Comment by michaelcassens** [comment]
Hi Rachel,

You might try: document.getElementById("myImage").src = "put in your object
source here"

Hope this helps!

Michael
