### ISSUE TITLE
putting this.image in img src

### ISSUE THREAD

**Issue by ghost** [Montana-Media-Arts/441-WebTech-Spring2019#15]
Hi all,

I have the code done & working, I just can't figure out how to get this.image to return correctly in my img src in my HTML file. No matter what I do it seems like it just returns outside my brackets, and not in my src, which is where I need it.
Any advice would be greatly appreciated!

My directory is here:  https://github.com/FinnVreugdenhil/441-work/tree/master/HW-7
And my Github Page is here: https://finnvreugdenhil.github.io/441-work/HW-7/

Thank you!

**Comment by michaelcassens** [comment]
Hi Finn,

Instead of innerHTML, you might try src.

Hope this helps!

Michael

**Comment by ghost** [comment]
You're a lifesaver as always, thank you!

**Comment by allenharguess701** [comment]
There was an issue i was having with the image url coming back scrambled. I console logged the element and got several unusual returns. it seemed to have something to do with the \. My code as an example, was

images\seven.jpg  

I would get returns back with the \ missing and several spaces added or a special character inserted just after the \ or the first letter of the image mane would be missing.  

Did i mention i hate java lol-
