### ISSUE TITLE
Hw-7

### ISSUE THREAD

**Issue by Dani-Briggs** [Montana-Media-Arts/441-WebTech-Spring2019#16]
Hello,
I'm having a little problem with my code. The problem involves a couple of things not popping up. The first thing is my hero-image, which is suppose to be a gray circle gradient. The second thing is the viewfinder. I click inspect in the browser and it says the mrViewFinder is not define, but I don't see what's wrong.
here's my code[https://github.com/Dani-Briggs/441/tree/master/Hw-7](url)

**Comment by michaelcassens** [comment]
Hi Dani,

So, on lines 56, 59, and 62, you have ViewFinder, but what you want is
ViewClass since that is what you called your class.  Also, you will want to
change the myViewFinderArrayOne and myViewFinderArrayTwo should be just
myViewFinderArray.

Hope this helps!

Michael
