### ISSUE TITLE
image won't pop up

### ISSUE THREAD

**Issue by Dani-Briggs** [Montana-Media-Arts/441-WebTech-Spring2019#18]
Hi again,
The problem I'm having this time is that my images will not show up. I not quite done with the homework, i'm testing some stuff, but I can get also everything else to show up but the images.
here's my code[https://github.com/Dani-Briggs/441/tree/master/Hw-8](url)
Thanks again!

**Comment by michaelcassens** [comment]
Hi Dani,

I will take a look as soon as I can.  I have a meeting this evening so I
might not see it until later.

Michael

**Comment by michaelcassens** [comment]
Hi Dani,

So, in your image tag, you just want to switch the "scr" to "src".

Hope this helps!

Michae
