### ISSUE TITLE
Can't get my second image to appear

### ISSUE THREAD

**Issue by rachel-holton-burnett** [Montana-Media-Arts/441-WebTech-Spring2019#19]
My heart won't show up in my array and I can not figure out what I am missing! 

var pineappleSelector = "#pineapple";
var heartSelector= "#heart";
var allPineapples = new Array();

class PineappleInfo{
    constructor(selector, imagePath)
    {
        this.selector = selector;
        this.imagePath = imagePath;
    }

    get theSelector(){
        return this.selector;
    }

    get theImagePath(){
        return this.imagePath;
    }

    toString()
    {
        return this.selector + ":" + this.imagePath;
    }
}

class HeartInfo{
    constructor(selector, imagePath)
    {
        this.selector = selector;
        this.imagePath = imagePath;
    }

    get theSelector(){
        return this.selector;
    }

    get theImagePath(){
        return this.imagePath;
    }

    toString()
    {
        return this.selector + ":" + this.imagePath;
    }
}

function initializeArray()
{
    var pineapple = new PineappleInfo("#pineapple", "images/pineapple2.png");

    var heart = new HeartInfo("#heart", "images/heart.png");

    allPineapples.push(pineapple);

    allPineapples.push(heart);
}

$(document).ready(function(){

    //$(allDogs[0].theSelector).src = allDogs[0].theImagePath;
    //$("#my_image").attr("src","second.jpg");
    $(allPineapples[0].theSelector).attr("src", allPineapples[0].theImagePath);

    $("button").click(function(){

        $(".first").fadeOut("slow").fadeIn("slow");
              setInterval(movePineapple, 1000);
              setInterval(moveHeart, 5000);
        $(".second").toggle().fadeOut("slow").fadeIn("slow");

        //$(allPineapples[0].theSelector).fadeOut("slow");

    });

});

function movePineapple()
{
    $("#pineapple").animate({left:1000}).fadeOut("slow").fadeIn("slow").animate({left:100});

}

function moveHeart()
{

    $("#heart").animate({left:20}).fadeOut("slow").fadeIn("slow").animate({left:1});
}

**Comment by michaelcassens** [comment]
Hi Rachel,

I will take a look as soon as I can.  I have a meeting this evening but can
look at it after I return.

Thanks,

Michael

**Comment by michaelcassens** [comment]
Hi Rachel,

So, on this line:

$(allPineapples[0].theSelector).attr("src", allPineapples[0].theImagePath);

You are getting the first item in which you added to the array which
was a pineapple.  If you switch it to [1], do you get the heart?


Hope this helps!


Michael
