### ISSUE TITLE
Wont link to JS

### ISSUE THREAD

**Issue by Zachberry777** [Montana-Media-Arts/441-WebTech-Spring2019#20]
![Screenshot (51)](https://user-images.githubusercontent.com/31712164/54170631-135bfc00-443d-11e9-87a5-dede1ef3ce9f.png)

**Comment by Zachberry777** [comment]
![Screenshot (52)](https://user-images.githubusercontent.com/31712164/54170992-77cb8b00-443e-11e9-908b-a342027878f4.png)
![Screenshot (53)](https://user-images.githubusercontent.com/31712164/54170995-7bf7a880-443e-11e9-8d2b-fe66bd8c2ace.png)
![Screenshot14](https://user-images.githubusercontent.com/31712164/54170997-7ef29900-443e-11e9-8097-cf9083f0ed4e.png)

**Comment by Zachberry777** [comment]
ignore the last picture

**Comment by MarkLannen** [comment]
Hey Zach
It looks like your .js file is on the same level as your .html and that there isn't a scripts folder? And I think the .css file is the same. Yet you reference both as if they were inside other folders.

If you change the css, does that have any effect on the page? If not, might be an indication that your references are incorrect.

Let me know if that helps!

**Comment by Zachberry777** [comment]
Yes that worked once i put them into separate folders. Thank you again for the help.

**Comment by MarkLannen** [comment]
Great!
