### ISSUE TITLE
getKey issues

### ISSUE THREAD

**Issue by jackelynstob** [Montana-Media-Arts/441-WebTech-Spring2019#23]
Hey all! I'm having a hard time with figuring out how to get the "getKey(event)" portion to work. Currently, I'm working through it on the website with our readings, but still struggling. 
I can get the box to move on it's own, but I can't get it to work where I press "w" to get it to move.
I'm not sure if I need to call the getKey(event) since I believe it's supposed to automatically get called when I press the 'w' key, but I'm not sure. 
Also in the moveUp(); function, I changed it from y-=10 to y=-10 because I believe that was just a typo. 

Please help a girl out! Thank you. 

Here's my code: 

HTML: 

<html>
    <head>
        <title>Canvas</title>
    </head>
    <style>
        #myCanvas{
            border:black;
            border-style: solid;
            border-width: 2px;

        }
    </style>
    <body>
        <canvas id="myCanvas" height="600" width="800"></canvas>

        <script>
            
            var canvas = document.getElementById("myCanvas");
            var ctx = canvas.getContext("2d");
            var x = 50;
            var y = 50;
            ctx.fillStyle = "#0000FF";
            drawSquare();
            setInterval(update, 1000/60);
            

            function update()
            {
                drawSquare();
                ctx.clearRect(0,0,800,600);
                drawSquare();
            }

            function drawSquare()
            {
                ctx.fillRect(x, y, 20, 20);
              //x++ moves the square to the right autonomously 
                x++;
            }
            
            function getKey(event)
            {
                var char = event.which || event.keyCode;
                var actualLetter = String.fromCharCode(char);
                if(actualLetter == "w")
                     {
                         moveUp();
                     }
                drawSquare();
            }

            function moveUp()
            {
                 y= -10;
            }

        </script>
    </body>
</html>

SCRIPT:

$(document).ready(function(){
    $(this).keypress(function(event){
        getKey(event);
    });
});

**Comment by MarkLannen** [comment]
Hi 

Have you referenced a jQuery library? I don't see it in your HTML.

Also, is your jQuery code in a separate script file somewhere else in your project? It would need to be either inside the script tag above or in a script folder that was referenced in the HTML.

I hope that helps!
