### ISSUE TITLE
Moving object on own

### ISSUE THREAD

**Issue by rachel-holton-burnett** [Montana-Media-Arts/441-WebTech-Spring2019#24]
I can't even get the first part of this assignment completed and it is making me so frustrated. I changed the color of the square because I was just testing it. I know that I am really close but no matter what I try it just makes another square appear instead of moving the square that I have. 

This is what I have: 

<!DOCTYPE html>
<html>
    <head>
        <title>Canvas</title>
    </head>
    <style>
        #myCanvas{
            border:black;
            border-style: solid;
            border-width: 2px;

        }
    </style>
    <body>
        <canvas id="myCanvas" height="600" width="800"></canvas>

        <script>
            var canvas = document.getElementById("myCanvas");
            var ctx = canvas.getContext("2d");
            var x = 50;
            var y = 50;
            ctx.fillStyle = "#0000FF";
            drawSquare();

            setInterval(update, 1000);

            function update()
            {
                drawSquare();
                //ctx.clearRect(0,0,800,600);

            }

            function drawSquare()
            {
                ctx.fillRect(x, y, 20, 20);

                ctx.fillStyle = "red";

            }

        </script>
    </body>
</html>

**Comment by michaelcassens** [comment]
Hi Rachel,

I can give you a more detailed email tomorrow but essentially you need a
square class and the key events and then this should work.

Michael

**Comment by michaelcassens** [comment]
Hi Rachel,

I created a starting point for you with comments.  Hope this helps!

Michael
