### ISSUE TITLE
Week 13

### ISSUE THREAD

**Issue by Zachberry777** [Montana-Media-Arts/441-WebTech-Spring2019#26]
It wont let me see what im doing.
![Screenshot (61)](https://user-images.githubusercontent.com/31712164/56404437-f5479f80-6223-11e9-9937-1746cde4a25d.png)
![Screenshot (62)](https://user-images.githubusercontent.com/31712164/56404441-f8db2680-6223-11e9-9725-aac15faa7a00.png)
![Screenshot (63)](https://user-images.githubusercontent.com/31712164/56404446-fb3d8080-6223-11e9-9682-a38f9f2700ac.png)
![Screenshot14](https://user-images.githubusercontent.com/31712164/56404447-fd9fda80-6223-11e9-87c2-79e9d0c0498b.png)

**Comment by Zachberry777** [comment]
ignore the last picture

**Comment by kaitlinclifford** [comment]
honestly don't know if this would help you at all, but your jquery file isn't in a "libs" folder and you have it written as <script src="libs/jquery.min.js"></script> so try putting the jquery into a "libs" folder and let me know if that helps at all!
