### ISSUE TITLE
Pickup issue

### ISSUE THREAD

**Issue by ghost** [Montana-Media-Arts/441-WebTech-Spring2019#27]
Just debugging my assignment for this week. My code works, but only if the pickups are picked up in reverse array order. If you pick up the first pickup in the array first, it automatically hops the score up to 3 and gives the player a win.
I think the problem must be in my getKey function, specifically in the "if (test2 == true)" section. I've been fiddling with it, but I'm just not sure what this issue is.
My directory is [here](https://github.com/FinnVreugdenhil/441-work/tree/master/HW-11) and my GitHub page is [here](https://finnvreugdenhil.github.io/441-work/HW-11/).
Any help would be appreciated!

**Comment by michaelcassens** [comment]
Are you using pop? If so, it removes the last item added.  You might try
splice instead.

Hope this helps!

Michael

**Comment by ghost** [comment]
I was using pop! I changed it to splice and that fixed my score issue, but my last two pickups are still disappearing if I pick up the first in the array first. Any idea what that might be?

**Comment by michaelcassens** [comment]
Would you mind sharing what your splice looks like?

**Comment by ghost** [comment]
The links I posted above are updated and current, but here's the section in question.

![splice](https://user-images.githubusercontent.com/35827038/56446780-dd265d80-62c1-11e9-808c-eea55bb12c7b.JPG)

**Comment by michaelcassens** [comment]
Hi Finn,

Try putting a ,1 after the x in the splice

Hope this helps!

**Comment by ghost** [comment]
You saved me, as always. 
Have a good one, Michael!

**Comment by michaelcassens** [comment]
You too Finn!
