### ISSUE TITLE
Second JSON/Array not working 

### ISSUE THREAD

**Issue by jackelynstob** [Montana-Media-Arts/441-WebTech-Spring2019#28]
Hi gang! I'm working on my assignment now, I can't seem to get the second JSON to work and push through an array. I tried having my second JSON which I titled "food" in the same file as the squares and then again in it's own .json file. I'm not sure what I'm doing incorrectly but the food won't show up!!! Please let me know if you have any ideas thanks :) 
![Screen Shot 2019-04-19 at 8 29 13 PM](https://user-images.githubusercontent.com/31556621/56450271-fb03ba80-62e1-11e9-9a15-7fac1223b8e3.png)
![Screen Shot 2019-04-19 at 8 29 20 PM](https://user-images.githubusercontent.com/31556621/56450272-fb03ba80-62e1-11e9-8c05-be90faa70e2b.png)
![Screen Shot 2019-04-19 at 8 29 29 PM](https://user-images.githubusercontent.com/31556621/56450273-fb9c5100-62e1-11e9-8252-004849790cb5.png)
![Screen Shot 2019-04-19 at 8 29 53 PM](https://user-images.githubusercontent.com/31556621/56450274-fb9c5100-62e1-11e9-9547-2f082377d6cd.png)
![Screen Shot 2019-04-19 at 8 30 10 PM](https://user-images.githubusercontent.com/31556621/56450275-fb9c5100-62e1-11e9-9c3d-92b228daf253.png)

**Comment by michaelcassens** [comment]
Hi Jack,

You might try using ctx instead of using ctx1 since you only need one
context.

Hope this helps!

**Comment by jackelynstob** [comment]
@michaelcassens 
Hi Mr. Cassens!

I actually tried that RIGHT after posting this and it unfortunately didn't work :( Do you have any other ideas where I could be going wrong?

**Comment by michaelcassens** [comment]
Have you tried making sure there items in the array?  Right after your for
loop where you call getJSON print out the length of the array and make sure
it says 2.  Then, check when you are printing the array out that is goes
into the for loop (the drawFood)

**Comment by jackelynstob** [comment]
So the first part of your question it printed back to me that the foodArray.length is 2! Which is great because that's what it should be. But there must be a break in the second part of what you are telling me to do. I have the drawFood in the same spot as where we have drawSquare, is this what you are referencing?

**Comment by jackelynstob** [comment]
@michaelcassens 
So the first part of your question it printed back to me that the foodArray.length is 2! Which is great because that's what it should be. But there must be a break in the second part of what you are telling me to do. I have the drawFood in the same spot as where we have drawSquare, is this what you are referencing?

**Comment by michaelcassens** [comment]
Are you unable to print out anything in your drawFood function?

Michael

**Comment by jackelynstob** [comment]
@michaelcassens it printed out that the array length was also 2!!! in the drawFood function; but none of the yellow squares show up on the screen!!

**Comment by jackelynstob** [comment]
![Screen Shot 2019-04-19 at 9 22 58 PM](https://user-images.githubusercontent.com/31556621/56451527-6bfaa080-62e9-11e9-9b35-850a375c421a.png)
![Screen Shot 2019-04-19 at 9 23 18 PM](https://user-images.githubusercontent.com/31556621/56451529-6bfaa080-62e9-11e9-9161-248215851498.png)

**Comment by michaelcassens** [comment]
Okay so you might take a look at where and when you call clearRect.  Let me
know if that changes things!

Michael

**Comment by jackelynstob** [comment]
@michaelcassens yes thank you!!!! I got that working I really appreciate it!

**Comment by michaelcassens** [comment]
Great!
