### ISSUE TITLE
Live site not working correctly?

### ISSUE THREAD

**Issue by rachel-holton-burnett** [Montana-Media-Arts/441-WebTech-Spring2019#4]
My live site isn't loading the image or the correct color for my boxes. It should look like the picture attached. Any ideas?  

live site:
https://rachel-holton-burnett.github.io/441/HW1/

repo:
https://github.com/rachel-holton-burnett/441/tree/master/HW1 

![hw1](https://user-images.githubusercontent.com/31631405/51433566-58686c80-1c0a-11e9-9d3e-9e99f86e00d8.JPG)

**Comment by MarkLannen** [comment]
Hi Rachel

I have two suggestions.

1. In your images folder, the file extension is .JPG. but in your css file it is .jpg. Maybe try matching the case and see if that works?

2. Is your images folder at the same level as your index file? If that is the case then I don't think you need the ../ before the reference to your images file.

Let me know if that works!

**Comment by rachel-holton-burnett** [comment]
> Hi Rachel
> 
> I have two suggestions.
> 
> 1. In your images folder, the file extension is .JPG. but in your css file it is .jpg. Maybe try matching the case and see if that works?
> 2. Is your images folder at the same level as your index file? If that is the case then I don't think you need the ../ before the reference to your images file.
> 
> Let me know if that works!

Thank you Mark for the tips! That didn't work. The images folder is the same level and so I tried removing the ../ and it didn't work either (I actually tried removing each dot then all of it). This is the first time that when I open up the index page locally it works correctly in my browser but when I upload it to Github it's different. Really strange!

**Comment by allenharguess701** [comment]
I can see the image and cell color just fine. Try dumping your browser's cash memory by hold shift and clicking refresh

**Comment by rachel-holton-burnett** [comment]
> I can see the image and cell color just fine. Try dumping your browser's cash memory by hold shift and clicking refresh

Yes it's working now, thank you so much! This was driving me crazy!!
