### ISSUE TITLE
Files too large to push to Github

### ISSUE THREAD

**Issue by jackelynstob** [Montana-Media-Arts/441-WebTech-Spring2019#5]
I'm trying to push all of my edits to GitHub and it isn't working. My site is complete, but when I push it I keep getting an error message saying files size exceeds over 100MB and that I need to delete that file. I'm not sure what is it, do you guys know how I can go around this?

**Comment by jackelynstob** [comment]
I figured it out!!! :)

**Comment by michaelcassens** [comment]
Oh great!  What did you do?  Did you have to clear your cache?

**Comment by MarkLannen** [comment]
I had the same problem - would like to hear your solution!

**Comment by allenharguess701** [comment]
I also h as d this problem because I tried to upload video files that was linked to my media page. I removed both files and upload. Remember that you need to do a new commit after removing the offending files, then push the change
