### ISSUE TITLE
Homework 4

### ISSUE THREAD

**Issue by jackelynstob** [Montana-Media-Arts/441-WebTech-Spring2019#7]
I'm having a tiny bit of trouble with homework 4. Would anybody be willing to post an example of their code? I'm not entirely sure how to develop my homework 3.

**Comment by michaelcassens** [comment]
Hi there,

I will be posting an example later today along with a video.  Hopefully
that will help!

Michael

**Comment by ChristoffSomm** [comment]
Hey here is my code. It's a lot and very messy but I'll post it anyway. (I'm not done yet)
https://github.com/ChristoffSomm/MART_441-Web_Technologies/blob/master/HW3-4/index.html

I wrote a quick a quick HTML file for you to look at.
I hope it explains what I'm doing. 
https://github.com/ChristoffSomm/MART_441-Web_Technologies/blob/master/HelpCode/Example.html

My way is most likely not the most efficient way but it's one way.   


I'm so sorry about my spelling.

**Comment by michaelcassens** [comment]
Hi Christoffer,

Wow!  That was serious!  I will take a closer look when I am in front of a
computer again.  Thanks!

**Comment by jackelynstob** [comment]
@ChristoffSomm thank you so much! that's amazing. I'm gonna take a look at this and see how I can add it to my code. :)

**Comment by allenharguess701** [comment]
This is my answer to the assignment

https://github.com/allenharguess701/Mart441/tree/master/HW-4
