### ISSUE TITLE
Hw-4 

### ISSUE THREAD

**Issue by Dani-Briggs** [Montana-Media-Arts/441-WebTech-Spring2019#8]
Hi Everyone
I'm have trouble with the text box not showing up. It shows up for the first choice, but not for the second one. I'm following along with the example video and I have no idea what's wrong with it. To get to the second choice , choose Leave for the first choice.
Here's my code:
[https://github.com/Dani-Briggs/441/blob/master/Hw-4/index.html](url)

**Comment by michaelcassens** [comment]
Hi Dani,

That was a good one!  What happened is that your div tag that has the id
(question) is overwriting everything else. So, if you take your textboxes
and buttons out of the div tag, it should work just fine.  Hope this helps!

**Comment by Dani-Briggs** [comment]
That worked thanks
