### ISSUE TITLE
HW-5 how do i fix this where it can find the file

### ISSUE THREAD

**Issue by Zachberry777** [Montana-Media-Arts/441-WebTech-Spring2019#9]
![screenshot 34](https://user-images.githubusercontent.com/31712164/52982282-84f6dc00-33a2-11e9-9db3-9a327f7117f8.png)
![screenshot 35](https://user-images.githubusercontent.com/31712164/52982284-8aecbd00-33a2-11e9-9e84-889c3990c21c.png)
![screenshot 36](https://user-images.githubusercontent.com/31712164/52982287-8d4f1700-33a2-11e9-83a8-74a467b63308.png)

**Comment by MarkLannen** [comment]
Hi Zachberry777

In your script tag in the html file, it looks like you are referencing the .js file with the relative path "scripts/main.js" I think that would work if there were a directory called 'scripts' that the .js file was located in. But I don't think your directory structure is set up that way. Try removing the reference to the scripts folder in the href attribute and see if that works,  i.e. href="main.js"

Same thing with your .css file reference.

Let me know if that works!

**Comment by kaitlinclifford** [comment]
With the way your code is written right now, in order for your page to find your images and CSS, you're most likely going to need to put your images in an "images" folder inside of your HW-5, as well as make a "styles" folder inside the HW-5 folder and put your main.css in there. It looks to me that you don't have either an "images" or a "styles" folder so your code can't find where to get the information from.
